Add `+nightly` to Cargo command to use nightly
I tried to run `cargo build --release`, but was met with the following error.
```
❯ cargo build --release
error: failed to load manifest for workspace member `/a-complicated-directory-structure/substrate-node-template/node`

Caused by:
  failed to parse manifest at `/a-complicated-directory-structure/substrate-node-template/node/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
```

Adding `+nightly` resolved this issue.